version: '2'
services:
  python_study:
    build:
      context: ./analyze_pycode
      dockerfile: dockerfile
    container_name: python_study
    volumes:
    - ./analyze_pycode:/root/analysis-visualization/analyze_pycode
    - ../crawl-preprocess-storage/storage:/root/crawl-preprocess-storage/storage
    command: python /root/analysis-visualization/analyze_pycode/torch_lstm.py
